{{- $fullName := include "vaultwarden.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  {{- with .Values.vaultwarden }}
  {{- with .accounts.register }}
  SIGNUPS_ALLOWED: {{ print "%t" .enabled | quote }}
  SIGNUPS_VERIFY: {{ print "%t" .verify | quote }}
  {{- if .domainAllowList }}
  SIGNUPS_DOMAINS_WHITELIST: {{ .domainAllowList | quote }}
  {{- end }}
  {{- end }}
  {{- with .accounts.invite }}
  INVITATIONS_ALLOWED: {{ print "%t" .enabled | quote }}
  INVITATION_ORG_NAME: {{ .inviter | default "Vaultwarden" }}
  INVITATION_EXPIRATION_HOURS: {{ .expiration | quote }}
  {{- end }}
  DOMAIN: {{ .domain | quote }}
  LOG_LEVEL: {{ .logLevel | quote }}
  {{- with .sends }}
  SENDS_ALLOWED: {{ print "%t" .enabled | quote }}
  {{- end }}
  {{- with .server }}
  ROCKET_ADDRESS: {{ .address | quote }}
  ROCKET_PORT: {{ .port | quote }}
  {{- end }}
  {{- with .smtp }}
  SMTP_HOST: {{ .host | quote }}
  SMTP_FROM: {{ .from.address | quote }}
  SMTP_FROM_NAME: {{ .from.name | quote }}
  SMTP_SECURITY: {{ .security | quote }}
  SMTP_PORT: {{ .port | quote }}
  SMTP_AUTH_MECHANISM: {{ .auth | quote }}
  {{- end }}
  {{- with .webVault }}
  WEB_VAULT_ENABLED: {{ print "%t" .enabled | quote }}
  WEB_VAULT_FOLDER: {{ .path | quote }}
  {{- end }}
  {{- with .websocket }}
  WEBSOCKET_ENABLED: {{ print "%t" .enabled | quote }}
  WEBSOCKET_ADDRESS: {{ .address | quote }}
  WEBSOCKET_PORT: {{ .port | quote }}
  {{- end }}
  {{- end }}
