{{- $fullName := include "vaultwarden.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  {{- with .Values.vaultwarden }}
  {{- with .accounts.register }}
  SIGNUPS_ALLOWED: {{ .enabled }}
  SIGNUPS_VERIFY: {{ .verify }}
  SIGNUPS_DOMAINS_WHITELIST: {{ .domainAllowList }}
  {{- end }}

  {{- with .accounts.invite }}
  INVITATIONS_ALLOWED: {{ .enabled }}
  INVITATION_ORG_NAME: {{ .inviter }}
  INVITATION_EXPIRATION_HOURS: {{ .expiration }}
  {{- end }}

  DOMAIN: {{ .domain }}

  LOG_LEVEL: {{ .logLevel }}

  {{- with .sends }}
  SENDS_ALLOWED: {{ .enabled }}
  {{- end }}

  {{- with .server }}
  ROCKET_ADDRESS: {{ .address }}
  ROCKET_PORT: {{ .port }}
  {{- end }}

  {{- with .smtp }}
  SMTP_HOST: {{ .host }}
  SMTP_FROM: {{ .from.address }}
  SMTP_FROM_NAME: {{ .from.name }}
  SMTP_SECURITY: {{ .security }}
  SMTP_PORT: {{ .port }}
  SMTP_AUTH_MECHANISM: {{ .auth }}
  {{- end }}

  {{- with .webVault }}
  WEB_VAULT_ENABLED: {{ .enabled }}
  WEB_VAULT_FOLDER: {{ .path }}
  {{- end }}

  {{- with .websocket }}
  WEBSOCKET_ENABLED: {{ .enabled }}
  WEBSOCKET_ADDRESS: {{ .address }}
  WEBSOCKET_PORT: {{ .port }}
  {{- end }}
  {{- end }}
