{{- $fullName := include "vaultwarden.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $fullName) | default dict -}}
{{- $data := (get $secret "data") | default dict  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.vaultwarden.admin }}
  {{- if .enabled }}
  {{- $adminToken := (get $data "ADMIN_TOKEN") | default .token | default (randAlphaNum 64) }}
  ADMIN_TOKEN: {{ $adminToken }}
  {{- end }}
  {{- end }}

  {{- with .Values.vaultwarden.smtp }}
  SMTP_USERNAME: {{ .username }}
  SMTP_PASSWORD: {{ .password }}
  {{- end }}

  {{- with .Values.vaultwarden.yubico }}
  {{- if .enabled }}
  YUBICO_CLIENT_ID: {{ .clientId }}
  YUBICO_SECRET_KEY: {{ .secret }}
  YUBICO_SERVER: {{ .server }}
  {{- end }}
  {{- end }}