apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.vaultwarden.websocket.enabled }}
    - port: {{ .Values.service.websocket }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    {{- end }}
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
