# Default values for vaultwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

vaultwarden:
  admin:
    enabled: true
    token: "" # ADMIN_TOKEN
  accounts:
    register:
      enabled: true # SIGNUPS_ALLOWED
      verify: true # SIGNUPS_VERIFY
      domainAllowList: "" # SIGNUPS_DOMAINS_WHITELIST
    invite:
      enabled: true # INVITATIONS_ALLOWED
      inviter: "" # INVITATION_ORG_NAME
      expiration: 120 # INVITATION_EXPIRATION_HOURS
  domain: "" # DOMAIN
  # The verbosity of the log output "trace", "debug", "info", "warn", "error" and "off"
  logLevel: info
  # Bitwarden Sends
  sends:
    enabled: true # SENDS_ALLOWED
  server:
    address: 0.0.0.0 # ROCKET_ADDRESS
  smtp:
    host: ""
    from:
      address: ""
      name: ""
    security: starttls
    port: 587
    username: ""
    password: ""
    auth: "Login" # SMTP_AUTH_MECHANISM
  # Web vault
  webVault:
    enabled: true
    path: "web-vault/"
  # Websocket notifications
  websocket:
    enabled: true
    address: 0.0.0.0
  yubico:
    enabled: false
    clientId: "" # YUBICO_CLIENT_ID
    secret: "" # YUBICO_SECRET_KEY
    server: "" # YUBICO_SERVER

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.27.0-alpine

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

persistentVolumeClaim:
  # Specifies whether a persistent volume claim should be created 
  create: true
  # Annotations to add to the persistent volume claim
  annotations: {}
  # The name of the persistent volume claim to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # The requested resource storage size of the persistent volume claim
  storage: 2Gi
  # The storage class name of the persistent volume claim
  storageClassName: ""


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  http: 8080
  websocket: 3012

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: chart-example.local
  paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
